### PR TITLE
fix encode multiple docs

### LINKED ISSUE #155: Bug: Multi resource yaml does not work since v0.26.1
Hi!

It seems that version 0.26.1 had introduced a bug processing multi resource yaml files.

**How to reproduce**
Create a file such as `example.yaml`:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
---
apiVersion: v1
kind: Secret
data:
  username: ref+sops://secrets.enc.yaml/#username
```

Running `vals eval -f manifests/example.yaml` outputs:
```
sops: successfully retrieved key=secrets.enc.yaml
null
```

On version `0.26.0` it works correctly:
```
sops: successfully retrieved key=secrets.enc.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
---
apiVersion: v1
data:
  username: ****
kind: Secret
```

### PR DESCRIPTION
**Pull request by jkroepke**
fixes #155

### CODE REVIEW

**Comment by yxxhero** [comment]
@jkroepke thanks so much. please fix DCO issue.

**Comment by yxxhero** [comment]
@jkroepke could you add some tests? thanks so much.

File: vals_test.go [hunk 1]
```diff
@@ -76,3 +77,42 @@ func TestQuotedEnv(t *testing.T) {
...
+kind: Secret
+`
+
+	tmpFile, err := os.CreateTemp("", "secrets.yaml")
+	defer os.Remove(tmpFile.Name())
+
+	_, err = tmpFile.WriteString(yamlDocs)
+	require.NoError(t, err)
+
+	require.NoError(t, err)
```
Comment (yxxhero) [inline vals_test.go]: duplicate code? @jkroepke

**Review by yxxhero — APPROVED** [review]
